// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAXX8wkLWnjcQpU_Fvbm-kzdM-ULrOy0sI',
  //   appId: '1:749568293308:web:d4ca25aa3762a5ae69d3b9',
  //   messagingSenderId: '749568293308',
  //   projectId: 'finjan-e1dbb',
  //   authDomain: 'finjan-e1dbb.firebaseapp.com',
  //   storageBucket: 'finjan-e1dbb.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7FEucq7phUvhj8_aa87ub1bcBy8rDSbE',
    appId: '1:851252640536:android:cdbc88d2e91acd9190fc6d',
    messagingSenderId: '851252640536',
    projectId: 'flutter-firebase-2fcfa',
    storageBucket: 'flutter-firebase-2fcfa.appspot.com',
  );




}